// Regression tests for review findings ING-01, ING-14, EXTRA-2, EXTRA-3 and EXTRA-4
// (dependency-graph resolution, master/component read failures, the partial-collection
// contract, derivation failure handling and the refresh workflow's push step).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Http } from '../src/lib/http.ts';
import type { RunRecord, SourceEnvelope } from '../src/lib/types.ts';
import type { Collector, Ctx } from '../src/ingest/framework.ts';
import { braveDeps, type BraveDepsSnapshot, type DepsData } from '../src/ingest/sources/deps.ts';
import { flags, type FlagsData } from '../src/ingest/sources/flags.ts';
import * as run from '../src/ingest/run.ts';
import { advisoryVerdicts } from '../src/derive/changes.ts';
import * as layout from '../src/site/layout.ts';

const NOW = '2026-10-08T20:00:00Z';
const OLD = '2026-10-01T00:00:00Z';
const CRATES_IO = 'registry+https://github.com/rust-lang/crates.io-index';
const SHA_A = 'a'.repeat(40);
const SHA_B = 'b'.repeat(40);
const LOCKFILE = 'third_party/rust/chromium_crates_io/Cargo.lock';
const CARGO = 'components/brave_wallet/browser/zcash/rust/Cargo.toml';
const RPC = 'components/brave_wallet/browser/zcash/zcash_rpc.cc';
const NETWORK = 'components/brave_wallet/browser/network_manager.cc';
const FEATURES = 'components/brave_wallet/common/features.cc';
const FEATURES_SRC = readFileSync(new URL('./fixtures/features.v1.97.56.cc', import.meta.url), 'utf8');

const quiet = () => {};
const env = <T>(data: T): SourceEnvelope<T> => ({ sourceId: 'fixture', schema: 1, retrievedAt: NOW, data });
const releasesWith = (tag: string) => env({ latest: [{ tag, channel: 'release', version: tag.slice(1) }] });

/** Raw-file server: path -> content (per ref when given as "ref:path"), anything else 404. */
function rawHttp(files: Record<string, string | ((ref: string) => string | null)>, log: string[] = []): Http {
  return new Http({
    sleep: async () => {},
    maxRetries: 0,
    fetch: (async (input: string | URL | Request) => {
      const url = String(input);
      log.push(url);
      const m = url.match(/^https:\/\/raw\.githubusercontent\.com\/brave\/brave-core\/([^/]+)\/(.+)$/);
      if (!m) return new Response('not found', { status: 404 });
      const ref = decodeURIComponent(m[1]);
      const f = files[m[2]];
      const body = typeof f === 'function' ? f(ref) : f;
      return body === undefined || body === null ? new Response('not found', { status: 404 }) : new Response(body);
    }) as typeof fetch,
  });
}

function ctxFor(http: Http, commitSha: () => Promise<string | null>, get: (id: string) => SourceEnvelope<unknown> | null = () => null): Ctx {
  return { now: NOW, trigger: 'test', log: quiet, http, gh: { commitSha: async () => commitSha() } as unknown as Ctx['gh'], get: get as Ctx['get'] };
}

function pkg(name: string, version: string, opts: { source?: string | null; deps?: string[]; multiline?: boolean } = {}): string {
  const src = opts.source === undefined ? CRATES_IO : opts.source;
  const lines = ['[[package]]', `name = "${name}"`, `version = "${version}"`];
  if (src) lines.push(`source = "${src}"`);
  if (opts.deps?.length) {
    if (opts.multiline === false) lines.push(`dependencies = [${opts.deps.map((d) => `"${d}"`).join(', ')}]`);
    else lines.push('dependencies = [', ...opts.deps.map((d) => ` "${d}",`), ']');
  }
  return lines.join('\n');
}
const lockOf = (...pkgs: string[]) => `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n${pkgs.join('\n\n')}\n`;
const ZCASH_TOML = '[package]\nname = "zcash"\nversion = "1.0.0"\n\n[dependencies]\norchard = { version = "0.13", default-features = false }\n';

async function depsAt(lock: string, extra: Record<string, string> = {}): Promise<{ snap: BraveDepsSnapshot; result: Awaited<ReturnType<typeof braveDeps.collect>> }> {
  const http = rawHttp({ [LOCKFILE]: lock, [CARGO]: ZCASH_TOML, DEPS: 'deps = {}', [NETWORK]: '"https://zcash.wallet.brave.com/"', [RPC]: '"/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo"', ...extra });
  const result = await braveDeps.collect(ctxFor(http, async () => SHA_A, (id) => (id === 'brave-releases' ? releasesWith('v1.2.3') : null)), null);
  return { snap: result.data.snapshots['v1.2.3'], result };
}

// ---------------------------------------------------------------------------
// ING-01: versions come from Brave's Zcash crate's dependency graph
// ---------------------------------------------------------------------------

test('ING-01: reviewer fixture: the orchard version Zcash reaches (0.13.0) is reported, not the newest vendored one, and the advisory stays affected', async () => {
  // Exact lock string from the review's reproduction (inline dependency arrays, no [package] in Cargo.toml).
  const lock = '[[package]]\nname="zcash"\nversion="1.0.0"\ndependencies=["orchard 0.13.0"]\n[[package]]\nname="orchard"\nversion="0.13.0"\nsource="registry+https://github.com/rust-lang/crates.io-index"\n[[package]]\nname="unrelated"\nversion="1.0.0"\ndependencies=["orchard 0.15.0"]\n[[package]]\nname="orchard"\nversion="0.15.0"\nsource="registry+https://github.com/rust-lang/crates.io-index"';
  const http = rawHttp({ [LOCKFILE]: lock, [CARGO]: '[dependencies]\norchard="0.13"' });
  const r = await braveDeps.collect(ctxFor(http, async () => null, (id) => (id === 'brave-releases' ? releasesWith('v1.2.3') : null)), null);
  const snap = r.data.snapshots['v1.2.3'];
  assert.deepEqual(snap.lock.orchard, { version: '0.13.0', source: 'crates.io' }, 'lock keeps its {version, source} shape with the reachable version');
  assert.equal(snap.requirements.orchard, '0.13');
  assert.equal(snap.resolution?.method, 'graph');
  assert.deepEqual(snap.resolution?.root, { name: 'zcash', version: '1.0.0', from: 'default' }, 'Cargo.toml without [package] falls back to the documented crate name');
  assert.deepEqual(
    snap.resolution?.candidates.orchard.map((c) => [c.version, c.reachable, c.direct]),
    [['0.13.0', true, true], ['0.15.0', false, false]],
    'every vendored version is kept as a candidate with its reachability',
  );
  assert.deepEqual(snap.resolution?.ambiguous, []);
  const advisory = { id: 'GHSA-test', aliases: [], summary: 's', severity: 'critical', packages: ['rust:orchard'], vulnerableRanges: ['orchard < 0.14.0'], patched: ['orchard 0.14.0'], publishedAt: null, updatedAt: null, withdrawnAt: null, url: 'https://example.invalid' };
  const v = advisoryVerdicts(advisory, r.data);
  assert.equal(v.affected, true, 'the vulnerable version the Zcash crate uses keeps the advisory affected');
  assert.match(v.details.join('\n'), /orchard 0\.13\.0 is in the vulnerable range/);
});

test('ING-01: direct dependency wins over a transitive duplicate; both stay visible as reachable candidates', async () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard 0.15.0', 'zcash_primitives'] }),
    pkg('orchard', '0.13.0'),
    pkg('orchard', '0.15.0'),
    pkg('zcash_primitives', '0.29.0', { source: null, deps: ['orchard 0.13.0'] }),
  );
  const { snap, result } = await depsAt(lock);
  assert.deepEqual(snap.lock.orchard, { version: '0.15.0', source: 'crates.io' });
  assert.deepEqual(snap.resolution?.candidates.orchard.map((c) => [c.version, c.reachable, c.direct]), [['0.13.0', true, false], ['0.15.0', true, true]]);
  assert.deepEqual(snap.resolution?.ambiguous, [], 'a single direct dependency is not ambiguous');
  assert.equal(result.partial, undefined, 'all files read and the graph resolved: a complete collection');
});

test('ING-01: two transitive versions and no direct one are flagged ambiguous, never silently "newest"', async () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['a', 'b', 'orchard'] }),
    pkg('a', '1.0.0', { deps: ['halo2_gadgets 0.5.0'] }),
    pkg('b', '1.0.0', { deps: ['halo2_gadgets 0.4.0'] }),
    pkg('halo2_gadgets', '0.4.0'),
    pkg('halo2_gadgets', '0.5.0'),
    pkg('orchard', '0.15.0'),
  );
  const { snap, result } = await depsAt(lock);
  assert.deepEqual(snap.lock.halo2_gadgets, { version: '0.4.0', source: 'crates.io' }, 'the lowest reachable version is reported for advisory checks');
  assert.deepEqual(snap.resolution?.ambiguous, ['halo2_gadgets']);
  assert.ok(result.limitations?.some((l) => /halo2_gadgets resolves to several versions \(0\.4\.0, 0\.5\.0\)/.test(l)), 'ambiguity is reported');
});

test('ING-01: prerelease vs stable and same version from different sources are matched exactly', async () => {
  const GIT = 'git+https://github.com/zcash/orchard?rev=abc#abc';
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: [`orchard 0.13.0 (${GIT})`, 'zcash_client_backend 0.24.0'] }),
    pkg('orchard', '0.13.0'),
    pkg('orchard', '0.13.0', { source: GIT }),
    pkg('zcash_client_backend', '0.24.0', { source: null }),
    pkg('zcash_client_backend', '0.24.0-rc.1', { source: null }),
    pkg('other_wallet', '1.0.0', { deps: ['zcash_client_backend 0.24.0-rc.1', `orchard 0.13.0 (${CRATES_IO})`] }),
  );
  const { snap } = await depsAt(lock);
  assert.deepEqual(snap.lock.zcash_client_backend, { version: '0.24.0', source: 'path' }, 'stable 0.24.0 is what zcash uses, not the rc another crate uses');
  assert.deepEqual(snap.lock.orchard, { version: '0.13.0', source: 'other' }, 'the git source named in the dependency entry is the one reported');
});

test('ING-01: real Cargo.lock layout (multi-line arrays, metadata) resolves through transitive edges; unreachable crates are not reported as Brave\'s', async () => {
  const lock = `${lockOf(
    pkg('chromium', '0.1.0', { source: null, deps: ['zcash', 'sinsemilla'] }),
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard', 'zcash_client_backend'] }),
    pkg('orchard', '0.15.0', { deps: ['halo2_gadgets', 'pasta_curves 0.5.1'] }),
    pkg('halo2_gadgets', '0.5.0', { deps: ['pasta_curves 0.5.1'], multiline: false }),
    pkg('pasta_curves', '0.5.1'),
    pkg('pasta_curves', '0.4.0'),
    pkg('zcash_client_backend', '0.24.0-rc.1', { source: null, deps: ['shardtree'] }),
    pkg('shardtree', '0.7.0'),
    pkg('sinsemilla', '0.1.0'),
  )}\n[metadata]\n"checksum x" = "y"\n`;
  const { snap } = await depsAt(lock);
  assert.equal(snap.lock.pasta_curves?.version, '0.5.1');
  assert.equal(snap.lock.halo2_gadgets?.version, '0.5.0');
  assert.equal(snap.lock.shardtree?.version, '0.7.0');
  assert.equal(snap.lock.sinsemilla, undefined, 'only reached through the chromium workspace crate, not through zcash');
  assert.deepEqual(snap.resolution?.unreachable, ['sinsemilla']);
  assert.deepEqual(snap.resolution?.unresolvedEdges, []);
});

test('ING-01: without the Zcash crate in Cargo.lock nothing is dropped; duplicates are flagged and the collection is partial', async () => {
  const lock = lockOf(pkg('orchard', '0.13.0'), pkg('orchard', '0.15.0'), pkg('shardtree', '0.7.0'));
  const { snap, result } = await depsAt(lock);
  assert.equal(snap.resolution?.method, 'lockfile');
  assert.deepEqual(snap.lock.shardtree, { version: '0.7.0', source: 'crates.io' }, 'a unique version is kept');
  assert.equal(snap.lock.orchard?.version, '0.13.0');
  assert.deepEqual(snap.resolution?.ambiguous, ['orchard']);
  assert.ok(snap.resolution?.candidates.orchard.every((c) => c.reachable === null), 'reachability is unknown, not false');
  assert.equal(result.partial, true);
  assert.ok(result.limitations?.some((l) => /crate "zcash" not found/.test(l)));
});

test('ING-01: snapshots cached by the old newest-version selection are re-read and re-resolved', async () => {
  const lock = '[[package]]\nname="zcash"\nversion="1.0.0"\ndependencies=["orchard 0.13.0"]\n[[package]]\nname="orchard"\nversion="0.13.0"\nsource="registry+https://github.com/rust-lang/crates.io-index"\n[[package]]\nname="unrelated"\nversion="1.0.0"\ndependencies=["orchard 0.15.0"]\n[[package]]\nname="orchard"\nversion="0.15.0"\nsource="registry+https://github.com/rust-lang/crates.io-index"';
  const legacy: BraveDepsSnapshot = { ref: 'v1.2.3', commitSha: null, channels: ['github/release'], lock: { orchard: { version: '0.15.0', source: 'crates.io' } }, requirements: { orchard: '0.13' }, forkPin: null, endpoints: [], rpcMethods: ['GetLightdInfo'], retrievedAt: OLD, links: { lockfile: '', deps: '', cargo: '' } };
  const seen: string[] = [];
  const http = rawHttp({ [LOCKFILE]: lock, [CARGO]: ZCASH_TOML, DEPS: 'x', [NETWORK]: 'x', [RPC]: '"/CompactTxStreamer/GetLightdInfo"' }, seen);
  const r = await braveDeps.collect(ctxFor(http, async () => null, (id) => (id === 'brave-releases' ? releasesWith('v1.2.3') : null)), { snapshots: { 'v1.2.3': legacy } });
  assert.ok(seen.some((u) => u.endsWith('Cargo.lock')), 'the legacy snapshot was re-read');
  assert.equal(r.data.snapshots['v1.2.3'].lock.orchard.version, '0.13.0');
  assert.equal(r.data.snapshots['v1.2.3'].resolver, 2);
});

// ---------------------------------------------------------------------------
// ING-14: master and component read failures are partial and keep last good data
// ---------------------------------------------------------------------------

const oldMasterFlags = (): FlagsData => ({
  snapshots: { master: { tag: 'master', channel: 'nightly', version: 'master', file: FEATURES, permalink: 'https://example.invalid', flags: [{ name: 'kBraveWalletZCashFeature', kind: 'feature', key: 'BraveWalletZCash', feature: null, defaults: { desktop: true, android: true, ios: true } } as any], commitSha: 'old', retrievedAt: OLD } },
  checks: {},
});

test('ING-14: flags: unresolved master commit is partial and keeps the old master record and its observation time', async () => {
  const r = await flags.collect(ctxFor(rawHttp({}), async () => null), oldMasterFlags());
  assert.equal(r.partial, true);
  assert.equal(r.data.snapshots.master.retrievedAt, OLD);
  assert.equal(r.data.snapshots.master.commitSha, 'old');
  assert.ok(r.limitations?.some((l) => /master commit could not be resolved; master flags kept from 2026-10-01T00:00:00Z/.test(l)));
});

test('ING-14: flags: missing features.cc, an unparseable file or a failing request at master keep the old record', async () => {
  const missing = await flags.collect(ctxFor(rawHttp({}), async () => SHA_A), oldMasterFlags());
  assert.equal(missing.partial, true);
  assert.equal(missing.data.snapshots.master.retrievedAt, OLD);
  assert.ok(missing.limitations?.some((l) => /not found at aaaaaaaaaa/.test(l)));

  const garbled = await flags.collect(ctxFor(rawHttp({ [FEATURES]: '// refactored, no BASE_FEATURE here\n' }), async () => SHA_A), oldMasterFlags());
  assert.equal(garbled.partial, true);
  assert.equal(garbled.data.snapshots.master.flags.length, 1, 'an empty parse does not replace the last good flags');

  const outage = await flags.collect(ctxFor(rawHttp({}), async () => { throw new Error('HTTP 502'); }), oldMasterFlags());
  assert.equal(outage.partial, true, 'a master outage does not fail the whole collection');
  assert.equal(outage.data.snapshots.master.commitSha, 'old');

  const ok = await flags.collect(ctxFor(rawHttp({ [FEATURES]: FEATURES_SRC }), async () => SHA_A), oldMasterFlags());
  assert.equal(ok.partial, undefined);
  assert.equal(ok.data.snapshots.master.commitSha, SHA_A);
  assert.equal(ok.data.snapshots.master.retrievedAt, NOW);
});

test('ING-14: deps: unresolved master commit is partial and keeps the old master snapshot with its own time and commit', async () => {
  const oldMaster: BraveDepsSnapshot = { ref: 'master', commitSha: SHA_B, channels: ['master'], lock: { orchard: { version: '0.15.0', source: 'crates.io' } }, requirements: {}, forkPin: null, endpoints: ['https://zcash.wallet.brave.com/'], rpcMethods: [], retrievedAt: OLD, links: { lockfile: '', deps: '', cargo: '' } };
  const r = await braveDeps.collect(ctxFor(rawHttp({}), async () => null), { snapshots: { master: oldMaster } });
  assert.equal(r.partial, true);
  assert.deepEqual(r.data.snapshots.master, oldMaster);
  assert.ok(r.limitations?.some((l) => /master could not be resolved .*master pins kept from 2026-10-01T00:00:00Z \(commit bbbbbbbbbb\)/.test(l)));
});

test('ING-14: deps: a tag read without Cargo.toml/DEPS is partial, is not cached, and is completed when the files come back', async () => {
  const lock = lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'));
  const DEPS_TEXT = '"components/brave_wallet/browser/zcash/rust/librustzcash/src": "https://github.com/brave/librustzcash.git@' + 'c'.repeat(40) + '", # brave_ironwood_support';
  const files: Record<string, string> = { [LOCKFILE]: lock, [NETWORK]: '"https://zcash.wallet.brave.com/"', [RPC]: '"/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo"' };
  const get = (id: string) => (id === 'brave-releases' ? releasesWith('v1.2.3') : null);
  const r1 = await braveDeps.collect(ctxFor(rawHttp(files), async () => null, get), null);
  const s1 = r1.data.snapshots['v1.2.3'];
  assert.equal(r1.partial, true);
  assert.deepEqual(s1.missing, ['cargo', 'deps']);
  assert.deepEqual(s1.rpcMethods, ['GetLightdInfo'], 'rpc was read, so the old "complete" marker alone would have cached this tag');
  assert.ok(r1.limitations?.some((l) => /Cargo\.toml not found/.test(l)) && r1.limitations?.some((l) => /DEPS not found/.test(l)));

  const seen: string[] = [];
  const r2 = await braveDeps.collect(ctxFor(rawHttp({ ...files, [CARGO]: ZCASH_TOML, DEPS: DEPS_TEXT }, seen), async () => null, get), r1.data);
  const s2 = r2.data.snapshots['v1.2.3'];
  assert.ok(seen.some((u) => u.includes('/v1.2.3/') && u.endsWith('Cargo.toml')), 'the incomplete tag was re-read');
  assert.equal(s2.requirements.orchard, '0.13');
  assert.deepEqual(s2.forkPin, { repo: 'brave/librustzcash', sha: 'c'.repeat(40), comment: 'brave_ironwood_support' });
  assert.equal(s2.missing, undefined);

  const seen3: string[] = [];
  await braveDeps.collect(ctxFor(rawHttp({ ...files, [CARGO]: ZCASH_TOML, DEPS: DEPS_TEXT }, seen3), async () => null, get), r2.data);
  assert.ok(!seen3.some((u) => u.includes('/v1.2.3/')), 'a complete tag snapshot is cached');
});

test('ING-14: deps: a component missing at a new master commit keeps the last good value with its provenance', async () => {
  const lock = lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'));
  const oldMaster: BraveDepsSnapshot = { ref: 'master', commitSha: SHA_B, channels: ['master'], lock: { orchard: { version: '0.15.0', source: 'crates.io' } }, requirements: {}, forkPin: null, endpoints: ['https://zcash.wallet.brave.com/'], rpcMethods: [], retrievedAt: OLD, links: { lockfile: '', deps: '', cargo: '' } };
  const http = rawHttp({ [LOCKFILE]: lock, [CARGO]: ZCASH_TOML, DEPS: 'x', [RPC]: 'x' });
  const r = await braveDeps.collect(ctxFor(http, async () => SHA_A), { snapshots: { master: oldMaster } });
  const m = r.data.snapshots.master;
  assert.equal(r.partial, true);
  assert.equal(m.commitSha, SHA_A);
  assert.deepEqual(m.endpoints, ['https://zcash.wallet.brave.com/'], 'endpoints are not blanked');
  assert.deepEqual(m.missing, ['network']);
  assert.deepEqual(m.carriedFrom?.network, { commitSha: SHA_B, retrievedAt: OLD });
});

test('ING-14: deps: an unreadable master (missing Cargo.lock or server errors) is partial and keeps the old master snapshot unchanged', async () => {
  const oldMaster: BraveDepsSnapshot = { ref: 'master', commitSha: SHA_B, channels: ['master'], lock: { orchard: { version: '0.15.0', source: 'crates.io' } }, requirements: { orchard: '0.15' }, forkPin: null, endpoints: ['https://zcash.wallet.brave.com/'], rpcMethods: ['GetLightdInfo'], retrievedAt: OLD, links: { lockfile: '', deps: '', cargo: '' } };
  const gone = await braveDeps.collect(ctxFor(rawHttp({}), async () => SHA_A), { snapshots: { master: oldMaster } });
  assert.equal(gone.partial, true);
  assert.deepEqual(gone.data.snapshots.master, oldMaster, 'old record and old observation time');
  assert.ok(gone.limitations?.some((l) => /master: read failed .*Cargo\.lock missing at master.*kept the snapshot read 2026-10-01T00:00:00Z \(commit bbbbbbbbbb\)/.test(l)));

  const down = new Http({ sleep: async () => {}, maxRetries: 0, fetch: (async () => new Response('down', { status: 503 })) as typeof fetch });
  const outage = await braveDeps.collect(ctxFor(down, async () => SHA_A), { snapshots: { master: oldMaster } });
  assert.equal(outage.partial, true);
  assert.deepEqual(outage.data.snapshots.master, oldMaster);
});

// Guard (passes before and after the fix): per-ref error handling must not turn a run in which
// nothing could be read, and nothing earlier exists to keep, into a partial "success".
test('ING-14: deps: a network failure with no earlier data is still a failure, not a fresh success', async () => {
  const http = new Http({ sleep: async () => {}, maxRetries: 0, fetch: (async () => new Response('down', { status: 503 })) as typeof fetch });
  await assert.rejects(braveDeps.collect(ctxFor(http, async () => SHA_A), null), /HTTP 503/);
});

// ---------------------------------------------------------------------------
// EXTRA-2: partial collections never drop last good records silently
// ---------------------------------------------------------------------------

function withDataDir<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const dir = mkdtempSync(join(tmpdir(), 'zbt-audit-'));
  process.env.TRACKER_DATA_DIR = dir;
  return fn(dir).finally(() => {
    delete process.env.TRACKER_DATA_DIR;
    rmSync(dir, { recursive: true, force: true });
  });
}
const readData = (dir: string, ...p: string[]) => JSON.parse(readFileSync(join(dir, ...p), 'utf8'));
const scripted = (id: string, result: () => Awaited<ReturnType<Collector['collect']>>): Collector<any> => ({ id, name: `Fake ${id}`, url: 'https://example.invalid', schema: 1, async collect() { return result(); } });

test('EXTRA-2: a partial result that drops records keeps them, is recorded as partial, and does not advance lastCompleteAt', async () => {
  await withDataDir(async (dir) => {
    const opts = { now: '2026-10-08T10:00:00Z', trigger: 'test', token: null, log: quiet };
    await run.runRefresh({ ...opts, collectors: [scripted('src', () => ({ data: { items: { a: 1, b: 2 }, note: 'x' } }))] });
    const r2 = await run.runRefresh({ ...opts, now: '2026-10-08T12:00:00Z', collectors: [scripted('src', () => ({ data: { items: { a: 10 } }, partial: true }))] });
    assert.equal(r2.sources.src, 'partial');
    assert.equal(r2.outcome, 'partial');
    const e = readData(dir, 'sources', 'src.json');
    assert.deepEqual(e.data, { items: { a: 10, b: 2 }, note: 'x' }, 'fresh values kept, dropped record and field carried forward');
    assert.equal(e.partial, true);
    assert.equal(e.completeAt, '2026-10-08T10:00:00Z');
    const st = readData(dir, 'status.json').sources.src;
    assert.equal(st.lastOutcome, 'partial');
    assert.equal(st.lastCompleteAt, '2026-10-08T10:00:00Z');
    assert.equal(st.lastPartialAt, '2026-10-08T12:00:00Z');
    assert.equal(st.lastSuccessAt, '2026-10-08T12:00:00Z', 'lastSuccessAt keeps its meaning: last run that stored data');
    assert.ok(st.limitations.some((l: string) => /2 previously collected record\(s\).*items\.b, note/.test(l)), 'the carry-forward is stated, not silent');

    // Declared removals are honoured; complete results may remove records.
    await run.runRefresh({ ...opts, now: '2026-10-08T14:00:00Z', collectors: [scripted('src', () => ({ data: { items: { a: 11 }, note: 'x' }, partial: true, limitations: ['one read deferred'], removed: ['items.b'] }))] });
    assert.deepEqual(readData(dir, 'sources', 'src.json').data, { items: { a: 11 }, note: 'x' });
    assert.deepEqual(readData(dir, 'status.json').sources.src.limitations, ['one read deferred']);
    await run.runRefresh({ ...opts, now: '2026-10-08T16:00:00Z', collectors: [scripted('src', () => ({ data: { items: {} } }))] });
    const e4 = readData(dir, 'sources', 'src.json');
    assert.deepEqual(e4.data, { items: {} });
    assert.equal(e4.partial, undefined);
    assert.equal(e4.completeAt, '2026-10-08T16:00:00Z');
    assert.equal(readData(dir, 'status.json').sources.src.lastCompleteAt, '2026-10-08T16:00:00Z');
  });
});

test('EXTRA-2: a partial result with nothing dropped still states that it is partial', async () => {
  await withDataDir(async (dir) => {
    await run.runRefresh({ now: NOW, trigger: 'test', token: null, log: quiet, collectors: [scripted('src', () => ({ data: { v: 1 }, partial: true }))] });
    const st = readData(dir, 'status.json').sources.src;
    assert.equal(st.lastOutcome, 'partial');
    assert.equal(st.lastCompleteAt, null, 'never completed');
    assert.match(st.limitations.join(' '), /partial collection/);
  });
});

test('EXTRA-2: real flags collector through the orchestrator: a master outage keeps last good master flags and is recorded as partial', async () => {
  await withDataDir(async (dir) => {
    let masterOk = true;
    const fetchImpl = (async (input: string | URL | Request) => {
      const url = String(input);
      if (url.startsWith('https://api.github.com/repos/brave/brave-core/commits/master')) return masterOk ? new Response(SHA_A) : new Response('{"message":"Not Found"}', { status: 404 });
      if (url === `https://raw.githubusercontent.com/brave/brave-core/${SHA_A}/${FEATURES}`) return new Response(FEATURES_SRC);
      return new Response('not found', { status: 404 });
    }) as typeof fetch;
    const base = { trigger: 'test', token: null, log: quiet, fetchImpl, sleep: async () => {}, collectors: [flags] };
    await run.runRefresh({ ...base, now: '2026-10-08T10:00:00Z' });
    masterOk = false;
    const r2 = await run.runRefresh({ ...base, now: '2026-10-08T12:00:00Z' });
    assert.equal(r2.sources['brave-flags'], 'partial');
    const e = readData(dir, 'sources', 'brave-flags.json');
    assert.equal(e.data.snapshots.master.retrievedAt, '2026-10-08T10:00:00Z');
    assert.equal(e.data.snapshots.master.commitSha, SHA_A);
    assert.ok(e.data.snapshots.master.flags.some((f: { name: string }) => f.name === 'kBraveWalletZCashFeature'));
    const st = readData(dir, 'status.json').sources['brave-flags'];
    assert.equal(st.lastCompleteAt, '2026-10-08T10:00:00Z');
    assert.match(st.limitations.join(' '), /master commit could not be resolved/);
  });
});

// ---------------------------------------------------------------------------
// EXTRA-3: derivation failure fails the run and keeps the previously derived data
// ---------------------------------------------------------------------------

test('EXTRA-3: when deriveAll throws, the run fails (non-zero exit), the failure is recorded and site.json keeps its generatedAt', async () => {
  await withDataDir(async (dir) => {
    const base = { trigger: 'test', token: null, log: quiet, collectors: [scripted('alpha', () => ({ data: { v: 1 } }))] };
    const r1 = await run.runRefresh({ ...base, now: '2026-10-08T10:00:00Z' });
    assert.equal(r1.outcome, 'success');
    const siteBefore = readFileSync(join(dir, 'derived', 'site.json'));
    assert.equal(JSON.parse(siteBefore.toString()).generatedAt, '2026-10-08T10:00:00Z');

    // A real derivation failure: the change history it must read is corrupt.
    writeFileSync(join(dir, 'history', 'events.json'), '[{"broken": ');
    const r2 = await run.runRefresh({ ...base, now: '2026-10-08T12:00:00Z' });
    assert.equal(r2.sources.alpha, 'ok');
    assert.equal(r2.outcome, 'failed', 'nothing new was published, so the run failed');
    assert.equal(r2.derive?.outcome, 'failed');
    assert.match(r2.derive?.error ?? '', /Corrupt JSON/);
    assert.equal(run.refreshExitCode(r1), 0);
    assert.equal(run.refreshExitCode(r2), 1);
    assert.deepEqual(readFileSync(join(dir, 'derived', 'site.json')), siteBefore, 'derived data untouched; generatedAt shows its true age');
    const status = readData(dir, 'status.json');
    assert.equal(status.lastRun.outcome, 'failed');
    assert.equal(status.lastRun.derive.outcome, 'failed');
    assert.equal(status.derive.lastSuccessAt, '2026-10-08T10:00:00Z');
    assert.equal(status.derive.consecutiveFailures, 1);
    assert.equal(readData(dir, 'history', 'runs.json')[0].outcome, 'failed');
  });
});

test('EXTRA-3: files written by a derivation that fails part-way are restored byte for byte', async () => {
  await withDataDir(async (dir) => {
    const base = { trigger: 'test', token: null, log: quiet, collectors: [scripted('alpha', () => ({ data: { v: 1 } }))] };
    await run.runRefresh({ ...base, now: '2026-10-08T10:00:00Z' });
    const files = [['history', 'events.json'], ['derived', 'snapshot.json'], ['derived', 'site.json']].map((p) => join(dir, ...p));
    const before = files.map((f) => readFileSync(f));
    const r = await run.runRefresh({
      ...base,
      now: '2026-10-08T12:00:00Z',
      derive: () => {
        writeFileSync(files[0], '[]\n');
        writeFileSync(files[1], '{"at":"2026-10-08T12:00:00Z"}\n');
        writeFileSync(files[2], '{"generatedAt":"2026-10-08T12:00:00Z"}\n');
        writeFileSync(join(dir, 'derived', 'extra.json'), '{}');
        throw new Error('derive exploded after writing');
      },
    });
    assert.equal(r.outcome, 'failed');
    files.forEach((f, i) => assert.deepEqual(readFileSync(f), before[i], `${f} restored`));
    assert.equal(existsSync(join(dir, 'derived', 'extra.json')), false, 'files created by the failed derivation are removed');
    assert.match(readData(dir, 'history', 'runs.json')[0].notes.join(' '), /derive failed: Error: derive exploded after writing \(previously derived data kept\)/);
  });
});

test('EXTRA-3: exit code policy and the CLI exit status', async () => {
  const rec = (outcome: RunRecord['outcome'], derive: RunRecord['derive']): RunRecord => ({ id: 'x', startedAt: NOW, finishedAt: NOW, trigger: 't', outcome, sources: {}, requests: 0, events: 0, notes: [], derive });
  assert.equal(run.refreshExitCode(rec('success', { outcome: 'ok', error: null })), 0);
  assert.equal(run.refreshExitCode(rec('partial', { outcome: 'ok', error: null })), 0, 'a partial source outage still publishes');
  assert.equal(run.refreshExitCode(rec('partial', { outcome: 'failed', error: 'x' })), 1);
  assert.equal(run.refreshExitCode(rec('failed', undefined)), 1);

  // End to end: the CLI with every collector skipped (no network) and a corrupt history file.
  await withDataDir(async (dir) => {
    const script = new URL('../src/ingest/run.ts', import.meta.url).pathname;
    const cli = () => spawnSync(process.execPath, [script, '--only=none'], { env: { ...process.env, TRACKER_DATA_DIR: dir, GITHUB_TOKEN: '', GH_TOKEN: '', GITHUB_ACTIONS: '' }, encoding: 'utf8' });
    assert.equal(cli().status, 0, 'derivation succeeds on an empty data dir');
    writeFileSync(join(dir, 'history', 'events.json'), '{');
    assert.equal(cli().status, 1, 'derivation failure exits non-zero');
  });
});

test('EXTRA-3: pages carry a visible banner when the latest run failed or the shown data predates it', () => {
  const fresh = { generatedAt: '2026-10-08T10:00:00Z', lastRunOutcome: 'failed', lastRunAt: '2026-10-08T12:03:00Z', sources: [], mode: 'live' as const };
  const html = layout.page({ title: 'T', description: 'd', path: '', active: 'home' }, fresh, { value: '' } as any);
  assert.match(html, /Latest refresh failed\./);
  assert.match(html, /generated <time datetime="2026-10-08T10:00:00Z"/);
  assert.equal(layout.lastRunFailed({ generatedAt: '2026-10-08T10:00:00Z', lastRunOutcome: 'success', lastRunAt: '2026-10-08T10:04:00Z' }), false, 'a normal run');
  assert.equal(layout.lastRunFailed({ generatedAt: '2026-10-08T10:00:00Z', lastRunOutcome: 'partial', lastRunAt: '2026-10-08T10:20:00Z' }), false);
  assert.equal(layout.lastRunFailed({ generatedAt: '2026-10-08T10:00:00Z', lastRunOutcome: 'partial', lastRunAt: '2026-10-08T12:04:00Z' }), true, 'derived data older than the latest run');
  assert.doesNotMatch(layout.page({ title: 'T', description: 'd', path: '', active: 'home' }, { ...fresh, lastRunOutcome: 'success', lastRunAt: '2026-10-08T10:04:00Z' }, { value: '' } as any), /Latest refresh failed/);
});

// ---------------------------------------------------------------------------
// EXTRA-4: the workflow's commit step fails when every push attempt fails
// ---------------------------------------------------------------------------

function commitStepScript(): string {
  return stepScript('Commit refreshed data');
}

function stepScript(name: string): string {
  const yml = readFileSync(new URL('../.github/workflows/refresh.yml', import.meta.url), 'utf8');
  const lines = yml.split('\n');
  const start = lines.findIndex((l) => l.trim() === `- name: ${name}`);
  assert.ok(start >= 0, `step "${name}" present`);
  const runIdx = lines.findIndex((l, i) => i > start && /^\s+run: \|\s*$/.test(l));
  const indent = (l: string) => l.match(/^ */)![0].length;
  const body: string[] = [];
  const bodyIndent = indent(lines[runIdx + 1]);
  for (let i = runIdx + 1; i < lines.length; i++) {
    if (lines[i].trim() && indent(lines[i]) < bodyIndent) break;
    body.push(lines[i].slice(bodyIndent));
  }
  return body.join('\n');
}

function runCommitStep(git: { diffQuiet: boolean; pushSucceedsOnAttempt: number | null }): { status: number | null; out: string; pushes: number } {
  const dir = mkdtempSync(join(tmpdir(), 'zbt-push-'));
  try {
    const counter = join(dir, 'pushes');
    writeFileSync(counter, '0');
    // Stub git on PATH: no repository, credentials or remote is touched.
    const stub = `#!/bin/bash
case "$1" in
  config|add|commit) exit 0 ;;
  diff) exit ${git.diffQuiet ? 0 : 1} ;;
  push) n=$(( $(cat "${counter}") + 1 )); echo $n > "${counter}"; echo "SIMULATED_PUSH attempt $n"; ${git.pushSucceedsOnAttempt === null ? 'exit 1' : `[ $n -ge ${git.pushSucceedsOnAttempt} ] && exit 0 || exit 1`} ;;
  pull) echo SIMULATED_PULL; exit 0 ;;
esac
exit 2
`;
    writeFileSync(join(dir, 'git'), stub);
    chmodSync(join(dir, 'git'), 0o755);
    // GitHub Actions runs `run:` blocks with bash -e (and -o pipefail for shell: bash).
    const res = spawnSync('bash', ['--noprofile', '--norc', '-eo', 'pipefail', '-c', commitStepScript()], { env: { PATH: `${dir}:${process.env.PATH}`, GITHUB_EVENT_NAME: 'audit', GITHUB_RUN_ID: '0' }, encoding: 'utf8' });
    return { status: res.status, out: `${res.stdout}${res.stderr}`, pushes: Number(readFileSync(counter, 'utf8')) };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test('EXTRA-3: the workflow fails visibly with the recorded reason (derivation failure, failed sources, or no record)', () => {
  const script = stepScript('Report refresh failure');
  const runIn = (status: unknown | null) => {
    const dir = mkdtempSync(join(tmpdir(), 'zbt-report-'));
    try {
      if (status !== null) {
        mkdirSync(join(dir, 'data'));
        writeFileSync(join(dir, 'data', 'status.json'), JSON.stringify(status));
      }
      const res = spawnSync('bash', ['--noprofile', '--norc', '-eo', 'pipefail', '-c', script], { cwd: dir, env: { PATH: process.env.PATH }, encoding: 'utf8' });
      return { status: res.status, out: `${res.stdout}${res.stderr}` };
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };
  const derive = runIn({ lastRun: { id: 'abc123', startedAt: NOW, outcome: 'failed', sources: { alpha: 'ok', derive: 'failed' }, derive: { outcome: 'failed', error: 'Error: boom\nsecond line' } }, sources: {} });
  assert.equal(derive.status, 1);
  assert.match(derive.out, /^::error::Refresh failed \(last recorded run abc123 started 2026-10-08T20:00:00Z: derivation failed: Error: boom second line\)\. The published site keeps the previously derived data/m);
  const sources = runIn({ lastRun: { id: 'def456', startedAt: NOW, outcome: 'failed', sources: { alpha: 'failed', beta: 'skipped', gamma: 'ok' }, derive: { outcome: 'ok', error: null } }, sources: {} });
  assert.equal(sources.status, 1);
  assert.match(sources.out, /outcome failed; sources not ok: alpha=failed, beta=skipped\)/);
  const none = runIn(null);
  assert.equal(none.status, 1);
  assert.match(none.out, /::error::Refresh failed \(no run record was written\)/);
});

test('EXTRA-4: exhausted push retries fail the commit step; a later successful push and a no-change run succeed', () => {
  const failed = runCommitStep({ diffQuiet: false, pushSucceedsOnAttempt: null });
  assert.notEqual(failed.status, 0, `all pushes failed but the step succeeded:\n${failed.out}`);
  assert.equal(failed.pushes, 3);
  assert.match(failed.out, /::error::Could not push refreshed data after 3 attempts/);

  const retried = runCommitStep({ diffQuiet: false, pushSucceedsOnAttempt: 2 });
  assert.equal(retried.status, 0, retried.out);
  assert.equal(retried.pushes, 2);

  const unchanged = runCommitStep({ diffQuiet: true, pushSucceedsOnAttempt: null });
  assert.equal(unchanged.status, 0, unchanged.out);
  assert.equal(unchanged.pushes, 0);
});
