// Round-2 regression tests for the ingest-deps-run group: R-DEPS-LOCK, R-DEPS-AMB, R-DEPS-PKG,
// R-STATUS, R-EXTRA-2 and R-WF. Everything runs offline (injected fetch, stubbed binaries).
//
// Modules whose exports changed in this round are imported as namespaces so the file still loads
// on the pre-fix code and each test fails there on its own assertion.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Http } from '../src/lib/http.ts';
import type { SourceEnvelope } from '../src/lib/types.ts';
import type { Collector, Ctx } from '../src/ingest/framework.ts';
import * as deps from '../src/ingest/sources/deps.ts';
import type { BraveDepsSnapshot, DepsData } from '../src/ingest/sources/deps.ts';
import * as flagsModule from '../src/ingest/sources/flags.ts';
import type { FlagsData } from '../src/ingest/sources/flags.ts';
import { braveVersions } from '../src/ingest/sources/brave-versions.ts';
import { services } from '../src/ingest/sources/services.ts';
import { watch } from '../src/ingest/sources/watch.ts';
import * as run from '../src/ingest/run.ts';
import { satisfiesRange } from '../src/lib/util.ts';

const NOW = '2026-10-08T20:00:00Z';
const OLD = '2026-10-01T00:00:00Z';
const CRATES_IO = 'registry+https://github.com/rust-lang/crates.io-index';
const SHA_A = 'a'.repeat(40);
const SHA_B = 'b'.repeat(40);
const LOCKFILE = 'third_party/rust/chromium_crates_io/Cargo.lock';
const CARGO = 'components/brave_wallet/browser/zcash/rust/Cargo.toml';
const RPC = 'components/brave_wallet/browser/zcash/zcash_rpc.cc';
const NETWORK = 'components/brave_wallet/browser/network_manager.cc';
const FEATURES = 'components/brave_wallet/common/features.cc';
const FEATURES_SRC = readFileSync(new URL('./fixtures/features.v1.97.56.cc', import.meta.url), 'utf8');
const ZCASH_TOML = '[package]\nname = "zcash"\nversion = "1.0.0"\n\n[dependencies]\norchard = { version = "0.13", default-features = false }\n';
const FORK_DEPS = '  "components/brave_wallet/browser/zcash/rust/librustzcash/src": "https://github.com/brave/librustzcash.git@' + 'c'.repeat(40) + '", # brave_ironwood_support\n';

const quiet = () => {};
const env = <T>(data: T): SourceEnvelope<T> => ({ sourceId: 'fixture', schema: 1, retrievedAt: NOW, data });
const releasesWith = (tag: string) => env({ latest: [{ tag, channel: 'release', version: tag.slice(1) }] });
const releasesGet = (id: string) => (id === 'brave-releases' ? releasesWith('v1.2.3') : null);

/** Raw-file server for brave-core: path -> content (or per-ref function), anything else 404. */
function rawHttp(files: Record<string, string | null | ((ref: string) => string | null)>, log: string[] = []): Http {
  return new Http({
    sleep: async () => {},
    maxRetries: 0,
    fetch: (async (input: string | URL | Request) => {
      const url = String(input);
      log.push(url);
      const m = url.match(/^https:\/\/raw\.githubusercontent\.com\/brave\/brave-core\/([^/]+)\/(.+)$/);
      if (!m) return new Response('not found', { status: 404 });
      const f = files[m[2]];
      const body = typeof f === 'function' ? f(decodeURIComponent(m[1])) : f;
      return body === undefined || body === null ? new Response('not found', { status: 404 }) : new Response(body);
    }) as typeof fetch,
  });
}

function ctxFor(http: Http, commitSha: () => Promise<string | null>, get: (id: string) => SourceEnvelope<unknown> | null = () => null, now = NOW): Ctx {
  return { now, trigger: 'test', log: quiet, http, gh: { commitSha: async () => commitSha() } as unknown as Ctx['gh'], get: get as Ctx['get'] };
}

function pkg(name: string, version: string, opts: { source?: string | null; deps?: string[] } = {}): string {
  const src = opts.source === undefined ? CRATES_IO : opts.source;
  const lines = ['[[package]]', `name = "${name}"`, `version = "${version}"`];
  if (src) lines.push(`source = "${src}"`);
  if (opts.deps?.length) lines.push('dependencies = [', ...opts.deps.map((d) => ` "${d}",`), ']');
  return lines.join('\n');
}
const lockOf = (...pkgs: string[]) => `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n${pkgs.join('\n\n')}\n`;
const filesFor = (lock: string) => ({ [LOCKFILE]: lock, [CARGO]: ZCASH_TOML, DEPS: FORK_DEPS, [NETWORK]: '"https://zcash.wallet.brave.com/"', [RPC]: '"/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo"' });

async function collectTag(lock: string, prev: DepsData | null = null, seen: string[] = []) {
  const result = await deps.braveDeps.collect(ctxFor(rawHttp(filesFor(lock), seen), async () => null, releasesGet), prev);
  return { snap: result.data.snapshots['v1.2.3'], result };
}
const root = { name: 'zcash', version: '1.0.0', from: 'cargo-toml' as const };
const exposed = (s: Pick<BraveDepsSnapshot, 'lock' | 'resolution'>, crate: string, range: string) => deps.rangeExposure(s, crate, (v) => satisfiesRange(v, range)).exposed;

// ---------------------------------------------------------------------------
// R-DEPS-LOCK: `lock` holds the highest linked version; every version stays a candidate
// ---------------------------------------------------------------------------

test('R-DEPS-LOCK: several linked versions: lock is the highest, all stay candidates, and exposure still sees the lower one', async () => {
  // zcash -> orchard 0.13.0 directly and -> zcash_primitives -> orchard 0.15.0 transitively (not "direct wins").
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard 0.13.0', 'zcash_primitives'] }),
    pkg('orchard', '0.13.0'),
    pkg('orchard', '0.15.0'),
    pkg('zcash_primitives', '0.29.0', { source: null, deps: ['orchard 0.15.0'] }),
  );
  const { snap, result } = await collectTag(lock);
  assert.deepEqual(snap.lock.orchard, { version: '0.15.0', source: 'crates.io' }, 'Brave resolves orchard 0.15.0 (the highest linked), not the lowest');
  assert.deepEqual(snap.resolution?.candidates.orchard.map((c) => [c.version, c.reachable, c.direct]), [['0.13.0', true, true], ['0.15.0', true, false]]);
  assert.deepEqual(snap.resolution?.multiple, ['orchard']);
  assert.ok(result.limitations?.some((l) => /links 2 versions of orchard \(0\.13\.0 \(direct\), 0\.15\.0\).*"lock" lists 0\.15\.0, the highest/.test(l)), 'the note names the highest');
  assert.equal(exposed(snap, 'orchard', '< 0.14.0'), true, 'the lower linked version is still exposure');
  assert.equal(exposed(snap, 'orchard', '>= 0.16.0'), false);
});

test('R-DEPS-LOCK: highest uses SemVer precedence (0.10.0 > 0.9.0, 0.24.0 > 0.24.0-rc.1), not string order', () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['a', 'b', 'zcash_client_backend 0.24.0-rc.1', 'zcash_client_backend 0.24.0'] }),
    pkg('a', '1.0.0', { deps: ['zcash_protocol 0.9.0'] }),
    pkg('b', '1.0.0', { deps: ['zcash_protocol 0.10.0'] }),
    pkg('zcash_protocol', '0.9.0'),
    pkg('zcash_protocol', '0.10.0'),
    pkg('zcash_client_backend', '0.24.0', { source: null }),
    pkg('zcash_client_backend', '0.24.0-rc.1', { source: null }),
  );
  const r = deps.resolveZcashDependencies(lock, ['zcash_protocol', 'zcash_client_backend'], root);
  assert.equal(r.lock.zcash_protocol?.version, '0.10.0');
  assert.equal(r.lock.zcash_client_backend?.version, '0.24.0');
  assert.deepEqual(r.resolution.multiple, ['zcash_protocol', 'zcash_client_backend']);
});

test('R-DEPS-LOCK: without the graph lock is the highest candidate; with a confirmed version it is the highest confirmed one', () => {
  const noRoot = deps.resolveZcashDependencies(lockOf(pkg('orchard', '0.15.0'), pkg('orchard', '0.13.0')), ['orchard'], root);
  assert.equal(noRoot.resolution.method, 'lockfile');
  assert.equal(noRoot.lock.orchard?.version, '0.15.0', 'highest candidate in the lockfile fallback');
  assert.deepEqual(noRoot.resolution.candidates.orchard.map((c) => [c.version, c.reachable]), [['0.15.0', null], ['0.13.0', null]], 'both kept, reachability unknown');
  assert.equal(exposed(noRoot, 'orchard', '< 0.14.0'), null);

  // 0.13.0 confirmed, 0.15.0 only possible (an unmatched entry leaves the graph incomplete): the confirmed one.
  const partial = deps.resolveZcashDependencies(lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard 0.13.0', 'mystery 9.9.9'] }), pkg('orchard', '0.13.0'), pkg('orchard', '0.15.0')), ['orchard'], root);
  assert.equal(partial.lock.orchard?.version, '0.13.0', 'a possible version never outranks a confirmed one');
  assert.deepEqual(partial.resolution.ambiguous, ['orchard']);
});

test('R-DEPS-LOCK: a complete tag snapshot from the previous resolver (lowest in lock) is re-read and re-resolved', async () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard 0.13.0', 'zcash_primitives'] }),
    pkg('orchard', '0.13.0'),
    pkg('orchard', '0.15.0'),
    pkg('zcash_primitives', '0.29.0', { source: null, deps: ['orchard 0.15.0'] }),
  );
  const fresh = (await collectTag(lock)).snap;
  // What resolver 3 stored for the same lockfile: complete, cached forever, with the lowest version.
  const v3: BraveDepsSnapshot = { ...fresh, resolver: 3, lock: { ...fresh.lock, orchard: { version: '0.13.0', source: 'crates.io' } } };
  delete (v3 as { lockPackages?: string[] }).lockPackages;
  const seen: string[] = [];
  const { snap } = await collectTag(lock, { snapshots: { 'v1.2.3': v3 } }, seen);
  assert.ok(seen.some((u) => u.includes('/v1.2.3/') && u.endsWith('Cargo.lock')), 'the stored meaning changed, so the tag is read again');
  assert.equal(snap.lock.orchard.version, '0.15.0');
  assert.equal(snap.resolver, deps.DEPS_RESOLVER);
  assert.ok(deps.DEPS_RESOLVER >= 4);
});

// ---------------------------------------------------------------------------
// R-DEPS-AMB: a dependency entry matching several packages names none of them for certain
// ---------------------------------------------------------------------------

test('R-DEPS-AMB: a bare dependency entry matching two versions leaves both unknown (ambiguous), not linked ("multiple")', async () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard', 'halo2_gadgets'] }),
    pkg('orchard', '0.15.0'),
    pkg('halo2_gadgets', '0.4.0', { deps: ['pasta_curves 0.4.0'] }),
    pkg('halo2_gadgets', '0.5.0'),
    pkg('pasta_curves', '0.4.0'),
  );
  const r = deps.resolveZcashDependencies(lock, ['orchard', 'halo2_gadgets', 'pasta_curves'], root);
  assert.deepEqual(r.resolution.candidates.halo2_gadgets.map((c) => [c.version, c.reachable, c.direct]), [['0.4.0', null, null], ['0.5.0', null, null]], 'neither is known to be linked, nor known to be direct');
  assert.deepEqual(r.resolution.ambiguous, ['halo2_gadgets']);
  assert.deepEqual(r.resolution.multiple, [], 'not reported as certainly linking two versions');
  assert.deepEqual(r.resolution.unresolvedEdges, ['zcash 1.0.0 -> halo2_gadgets (2 matches)']);
  assert.deepEqual(r.resolution.candidates.pasta_curves.map((c) => c.reachable), [null], 'reached only through the ambiguous match: unknown, not linked');
  assert.deepEqual(r.resolution.candidates.orchard.map((c) => c.reachable), [true], 'the unambiguous entry still resolves');
  assert.equal(exposed(r, 'halo2_gadgets', '>= 0.5.0, < 0.5.1'), null, 'unknown, not affected');
  assert.equal(exposed(r, 'halo2_gadgets', '< 0.4.1'), null);
  assert.equal(exposed(r, 'halo2_gadgets', '>= 0.6.0'), null, 'not "unaffected" either');
  assert.equal(deps.linkedVersions(r, 'halo2_gadgets').certain, false);
});

test('R-DEPS-AMB: a version also reached through an unambiguous path stays linked; the other stays possible', () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard', 'a'] }),
    pkg('orchard', '0.15.0', { deps: ['halo2_gadgets 0.5.0'] }),
    pkg('a', '1.0.0', { deps: ['halo2_gadgets'] }),
    pkg('halo2_gadgets', '0.4.0'),
    pkg('halo2_gadgets', '0.5.0'),
  );
  const r = deps.resolveZcashDependencies(lock, ['halo2_gadgets'], root);
  assert.deepEqual(r.resolution.candidates.halo2_gadgets.map((c) => [c.version, c.reachable, c.direct]), [['0.4.0', null, false], ['0.5.0', true, false]]);
  assert.deepEqual(r.resolution.ambiguous, ['halo2_gadgets']);
  assert.deepEqual(r.resolution.multiple, []);
  assert.equal(r.lock.halo2_gadgets?.version, '0.5.0');
  assert.equal(exposed(r, 'halo2_gadgets', '>= 0.5.0'), true, 'the confirmed version in range is exposure');
  assert.equal(exposed(r, 'halo2_gadgets', '< 0.5.0'), null, 'the possible one keeps the answer unknown');
});

test('R-DEPS-AMB: through the collector the snapshot is partial, says which entry was ambiguous, and is re-read next run', async () => {
  const lock = lockOf(
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard', 'halo2_gadgets'] }),
    pkg('orchard', '0.15.0'),
    pkg('halo2_gadgets', '0.4.0'),
    pkg('halo2_gadgets', '0.5.0'),
  );
  const { snap, result } = await collectTag(lock);
  assert.equal(result.partial, true);
  assert.deepEqual(snap.resolution?.ambiguous, ['halo2_gadgets']);
  assert.ok(result.limitations?.some((l) => /could not be matched to exactly one package \(zcash 1\.0\.0 -> halo2_gadgets \(2 matches\)\)/.test(l)));
  assert.ok(result.limitations?.some((l) => /could not establish which halo2_gadgets versions .*0\.4\.0, 0\.5\.0 possible/.test(l)));
  const seen: string[] = [];
  await collectTag(lock, result.data, seen);
  assert.ok(seen.some((u) => u.includes('/v1.2.3/') && u.endsWith('Cargo.lock')), 'not cached as complete');
});

// ---------------------------------------------------------------------------
// R-DEPS-PKG: every package name in the full Cargo.lock is recorded
// ---------------------------------------------------------------------------

test('R-DEPS-PKG: every package in Cargo.lock is listed (sorted, unique, unmonitored ones included); absent ones are absent', async () => {
  const lock = lockOf(
    pkg('chromium', '0.1.0', { source: null, deps: ['zcash', 'serde'] }),
    pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }),
    pkg('orchard', '0.15.0'),
    pkg('serde', '1.0.200'),
    pkg('serde', '1.0.100'),
    pkg('adblock', '0.9.0'),
  );
  const result = await deps.braveDeps.collect(ctxFor(rawHttp(filesFor(lock)), async () => SHA_A, releasesGet), null);
  const snap = result.data.snapshots['v1.2.3'];
  assert.deepEqual(snap.lockPackages, ['adblock', 'chromium', 'orchard', 'serde', 'zcash']);
  assert.equal(snap.lockPackages?.includes('zebrad'), false, 'a package that is not in Cargo.lock is not listed');
  assert.equal(result.partial, undefined, 'complete');
  assert.equal(result.data.snapshots.master.lockPackages?.length, 5, 'master records it too');
});

test('R-DEPS-PKG: linkedVersions/rangeExposure: a package absent from the full list is certainly not linked; without the list it stays unknown', async () => {
  const lock = lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'), pkg('zebra-chain', '1.0.0'));
  const { snap } = await collectTag(lock);
  assert.deepEqual(deps.linkedVersions(snap, 'zebrad'), { versions: [], certain: true }, 'zebrad is not in Cargo.lock at all');
  assert.equal(exposed(snap, 'zebrad', '< 2.0.0'), false);
  assert.equal(deps.linkedVersions(snap, 'zebra_chain').certain, false, 'present (spelled with "-") but not inspected: unknown, never absent');
  assert.equal(exposed(snap, 'zebra-chain', '< 2.0.0'), null);
  assert.equal(exposed(snap, 'orchard', '< 0.16.0'), true, 'monitored crates are unchanged');
  const { lockPackages: _omit, ...older } = snap;
  assert.equal(deps.linkedVersions(older, 'zebrad').certain, false, 'snapshots without the list: unknown');
  assert.equal(exposed(older, 'zebrad', '< 2.0.0'), null);
});

test('R-DEPS-PKG: a lockfile with a [[package]] the parser cannot read records no list (unknown), is partial and is re-read', async () => {
  const lock = `${lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'))}\n[[package]]\nname = "zebrad"\nversion = 4\n`;
  const { snap, result } = await collectTag(lock);
  assert.equal(snap.lockPackages, undefined, 'a skipped package must not look absent');
  assert.equal(result.partial, true);
  assert.ok(result.limitations?.some((l) => /v1\.2\.3: not every \[\[package\]\] in .*Cargo\.lock could be parsed/.test(l)));
  assert.equal(deps.lockPackageNames(lock), null);
  const seen: string[] = [];
  await collectTag(lock, result.data, seen);
  assert.ok(seen.some((u) => u.includes('/v1.2.3/') && u.endsWith('Cargo.lock')), 'retried while the list is missing');
});

test('R-DEPS-PKG: a cached tag snapshot without the list is read again so the list is filled in', async () => {
  const lock = lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'), pkg('zebrad', '2.0.0'));
  const { snap } = await collectTag(lock);
  const cached = { ...snap };
  delete cached.lockPackages;
  const seen: string[] = [];
  const again = await collectTag(lock, { snapshots: { 'v1.2.3': cached } }, seen);
  assert.ok(seen.some((u) => u.includes('/v1.2.3/') && u.endsWith('Cargo.lock')));
  assert.deepEqual(again.snap.lockPackages, ['orchard', 'zcash', 'zebrad']);
});

// ---------------------------------------------------------------------------
// R-STATUS: 'failed' keeps meaning "nothing usable was read"; stale data is partial + staleSince
// ---------------------------------------------------------------------------

function withDataDir<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const dir = mkdtempSync(join(tmpdir(), 'zbt-audit2-'));
  process.env.TRACKER_DATA_DIR = dir;
  return fn(dir).finally(() => {
    delete process.env.TRACKER_DATA_DIR;
    rmSync(dir, { recursive: true, force: true });
  });
}
const readData = (dir: string, ...p: string[]) => JSON.parse(readFileSync(join(dir, ...p), 'utf8'));
const scripted = (id: string, result: () => Awaited<ReturnType<Collector['collect']>>): Collector<any> => ({ id, name: `Fake ${id}`, url: 'https://example.invalid', schema: 1, async collect() { return result(); } });

test('R-STATUS: kept data older than the staleness window is stored as partial with staleSince and a note naming what and since when; never "failed"', async () => {
  await withDataDir(async (dir) => {
    const base = { trigger: 'test', token: null, log: quiet };
    await run.runRefresh({ ...base, now: '2026-10-08T08:00:00Z', collectors: [scripted('src', () => ({ data: { v: 1 } }))] });
    const late = await run.runRefresh({
      ...base,
      now: '2026-10-08T17:00:00Z',
      collectors: [scripted('src', () => ({ data: { v: 2 }, partial: true, staleSince: '2026-10-08T08:00:00Z', staleWhat: 'brave-core master pins', limitations: ['master could not be resolved'] }) as any)],
    });
    assert.equal(late.sources.src, 'partial', 'usable data was read and stored');
    assert.equal(late.outcome, 'partial');
    assert.equal(run.refreshExitCode(late), 0);
    const st = readData(dir, 'status.json').sources.src;
    assert.equal(st.lastOutcome, 'partial');
    assert.equal(st.staleSince, '2026-10-08T08:00:00Z', 'explicit field the site can count');
    assert.equal(st.lastCompleteAt, '2026-10-08T08:00:00Z');
    assert.equal(st.lastPartialAt, '2026-10-08T17:00:00Z');
    assert.equal(st.lastError, null);
    assert.equal(st.consecutiveFailures, 0);
    assert.equal(st.limitations[0], 'stale: brave-core master pins could not be refreshed since 2026-10-08T08:00:00Z (9 h, longer than the 6-hour staleness window); the last good values are kept and shown. Last complete collection: 2026-10-08T08:00:00Z.');
    assert.equal(st.limitations[1], 'master could not be resolved');
    const e = readData(dir, 'sources', 'src.json');
    assert.deepEqual(e.data, { v: 2 });
    assert.equal(e.partial, true);
    assert.equal(e.completeAt, '2026-10-08T08:00:00Z');
  });
});

test('R-STATUS: "failed" means the envelope is untouched; staleSince is kept by a failure, absent within the window, cleared by a complete run', async () => {
  await withDataDir(async (dir) => {
    const base = { trigger: 'test', token: null, log: quiet };
    const status = () => readData(dir, 'status.json').sources.src;
    await run.runRefresh({ ...base, now: '2026-10-08T08:00:00Z', collectors: [scripted('src', () => ({ data: { v: 1 } }))] });
    // Within the window: partial, not stale.
    await run.runRefresh({ ...base, now: '2026-10-08T12:00:00Z', collectors: [scripted('src', () => ({ data: { v: 2 }, partial: true, staleSince: '2026-10-08T08:00:00Z' }))] });
    assert.equal(status().lastOutcome, 'partial');
    assert.equal(status().staleSince, undefined);
    // Beyond it: stale.
    await run.runRefresh({ ...base, now: '2026-10-08T15:00:00Z', collectors: [scripted('src', () => ({ data: { v: 3 }, partial: true, staleSince: '2026-10-08T08:00:00Z' }))] });
    assert.equal(status().lastOutcome, 'partial');
    assert.equal(status().staleSince, '2026-10-08T08:00:00Z');
    assert.match(status().limitations[0], /^stale: some values this source should refresh every run could not be refreshed since 2026-10-08T08:00:00Z \(7 h,/);
    // A collector that throws stores nothing: failed, envelope byte for byte unchanged, still stale since 08:00.
    const before = readFileSync(join(dir, 'sources', 'src.json'));
    const r = await run.runRefresh({ ...base, now: '2026-10-08T17:00:00Z', collectors: [scripted('src', () => { throw new Error('HTTP 503'); })] });
    assert.equal(r.sources.src, 'failed');
    assert.deepEqual(readFileSync(join(dir, 'sources', 'src.json')), before);
    assert.equal(status().lastOutcome, 'failed');
    assert.equal(status().lastError, 'Error: HTTP 503');
    assert.equal(status().staleSince, '2026-10-08T08:00:00Z');
    // A complete run clears it.
    await run.runRefresh({ ...base, now: '2026-10-08T19:00:00Z', collectors: [scripted('src', () => ({ data: { v: 4 } }))] });
    assert.equal(status().lastOutcome, 'ok');
    assert.equal(status().staleSince, undefined);
    assert.equal(status().lastCompleteAt, '2026-10-08T19:00:00Z');
  });
});

test('R-STATUS: invariant over the real deps and flags collectors: a source recorded "failed" never has a newly written envelope', async () => {
  await withDataDir(async (dir) => {
    let masterOk = true;
    const lock = lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'));
    const masterFiles: Record<string, string> = { ...filesFor(lock), [FEATURES]: FEATURES_SRC };
    const fetchImpl = (async (input: string | URL | Request) => {
      const url = String(input);
      if (url.startsWith('https://api.github.com/repos/brave/brave-core/commits/master')) return masterOk ? new Response(SHA_A) : new Response('{"message":"Server Error"}', { status: 404 });
      const m = url.match(/^https:\/\/raw\.githubusercontent\.com\/brave\/brave-core\/([^/]+)\/(.+)$/);
      if (m && decodeURIComponent(m[1]) === SHA_A && masterFiles[m[2]] !== undefined) return new Response(masterFiles[m[2]]);
      return new Response('not found', { status: 404 });
    }) as typeof fetch;
    const base = { trigger: 'test', token: null, log: quiet, fetchImpl, sleep: async () => {}, collectors: [flagsModule.flags, deps.braveDeps] };
    await run.runRefresh({ ...base, now: '2026-10-08T06:00:00Z' });
    masterOk = false;
    const runs = ['2026-10-08T10:00:00Z', '2026-10-08T14:00:00Z', '2026-10-08T18:00:00Z'];
    for (const now of runs) {
      const before = { flags: readFileSync(join(dir, 'sources', 'brave-flags.json')), deps: readFileSync(join(dir, 'sources', 'brave-deps.json')) };
      const r = await run.runRefresh({ ...base, now });
      for (const [id, file] of [['brave-flags', 'flags'], ['brave-deps', 'deps']] as const) {
        const changed = !readFileSync(join(dir, 'sources', `${id}.json`)).equals(before[file]);
        assert.notEqual(r.sources[id], 'failed', `${id} at ${now}: kept master data is a partial read, not a failure`);
        assert.ok(changed, `${id} at ${now}: data was stored`);
        assert.equal(r.sources[id], 'partial');
      }
    }
    const st = readData(dir, 'status.json').sources;
    assert.equal(st['brave-flags'].staleSince, '2026-10-08T06:00:00Z');
    assert.equal(st['brave-deps'].staleSince, '2026-10-08T06:00:00Z');
    assert.match(st['brave-flags'].limitations[0], /^stale: brave-core master feature flags \(components\/brave_wallet\/common\/features\.cc at commit aaaaaaaaaa\) could not be refreshed since 2026-10-08T06:00:00Z \(12 h,/);
    assert.match(st['brave-deps'].limitations[0], /^stale: brave-core master dependency snapshot \(third_party\/rust\/chromium_crates_io\/Cargo\.lock, DEPS, .*commit aaaaaaaaaa\) could not be refreshed since 2026-10-08T06:00:00Z \(12 h,/);
    assert.equal(st['brave-deps'].lastCompleteAt, '2026-10-08T06:00:00Z');
    assert.equal(readData(dir, 'sources', 'brave-deps.json').data.snapshots.master.retrievedAt, '2026-10-08T06:00:00Z', 'the kept master snapshot keeps its own read time');
  });
});

test('R-STATUS: deps names the kept master component when only a component file is stale', async () => {
  const lock = lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0'));
  const r0 = await deps.braveDeps.collect(ctxFor(rawHttp(filesFor(lock)), async () => SHA_A, () => null, '2026-10-08T06:00:00Z'), null);
  const r1 = await deps.braveDeps.collect(ctxFor(rawHttp({ ...filesFor(lock), [NETWORK]: null }), async () => SHA_B, () => null, '2026-10-08T14:00:00Z'), r0.data);
  assert.equal(r1.staleSince, '2026-10-08T06:00:00Z');
  assert.equal((r1 as { staleWhat?: string }).staleWhat, 'brave-core master Zcash endpoints (network_manager.cc)');
  const f = await flagsModule.flags.collect(ctxFor(rawHttp({}), async () => null), { snapshots: { master: { tag: 'master', channel: 'nightly', version: 'master', file: FEATURES, permalink: 'x', flags: [], commitSha: SHA_B, retrievedAt: OLD } }, checks: {} } as FlagsData);
  assert.equal((f as { staleWhat?: string }).staleWhat, 'brave-core master feature flags (components/brave_wallet/common/features.cc at commit bbbbbbbbbb)');
});

// ---------------------------------------------------------------------------
// R-EXTRA-2: the partial-collection contract end to end on the merged collectors
// ---------------------------------------------------------------------------

const DESKTOP_OS = ['windows-x64', 'windows-x86', 'windows-arm64', 'macos-x64', 'macos-arm64', 'linux-x64', 'linux-arm64'];
const STUDY = "[ { name: 'ZCashStudy_Enabled', experiment: [ { name: 'Enabled', probability_weight: 100, feature_association: { enable_feature: ['BraveWalletZCash'] } } ], filter: { channel: ['RELEASE'], platform: ['ANDROID'], min_version: '139.1.81.129' } } ]";
const GATE3 = 'from app.api.common.models import Chain\n\nSWAP_DISABLED_CHAINS: frozenset[Chain] = frozenset({Chain.ZCASH})\n';
const blobSha = (s: string) => {
  const b = Buffer.from(s);
  return createHash('sha1').update(`blob ${b.length}\0`).update(b).digest('hex');
};

/** versions.brave.com, GitHub (commits, contents, releases, search) and raw files for brave-versions, brave-services and watch. */
function servicesWorld(outage: boolean) {
  const versions: Record<string, string> = {};
  for (const ch of ['release', 'beta', 'nightly']) {
    const v = ch === 'release' ? '1.97.56' : ch === 'beta' ? '1.98.52' : '1.99.27';
    for (const os of DESKTOP_OS) versions[`${ch}-${os}`] = v;
    versions[`${ch}-android-google-play`] = ch === 'release' ? '1.96.61' : v;
    versions[ch === 'release' ? 'release-ios-app-store' : `${ch}-ios`] = ch === 'release' ? '1.96' : v;
  }
  const json = (o: unknown) => new Response(JSON.stringify(o), { headers: { 'content-type': 'application/json' } });
  return (async (input: string | URL | Request) => {
    const url = String(input);
    const pointer = url.match(/^https:\/\/versions\.brave\.com\/latest\/(.+)\.version$/);
    if (pointer) {
      // Outage: only one pointer answers (the reviewer's literal trigger).
      if (outage && pointer[1] !== 'release-windows-x64') return new Response('unavailable', { status: 503 });
      return versions[pointer[1]] ? new Response(versions[pointer[1]]) : new Response('', { status: 404 });
    }
    if (url.startsWith('https://api.github.com/search/issues')) return json({ total_count: 0, incomplete_results: false, items: [] });
    if (url === 'https://api.github.com/repos/brave/gate3/commits/master') return new Response(SHA_A);
    if (url === `https://raw.githubusercontent.com/brave/gate3/${SHA_A}/app/api/swap/constants.py`) return new Response(GATE3);
    // Outage: brave-variations unreachable.
    if (url === 'https://api.github.com/repos/brave/brave-variations/commits/main') return outage ? new Response('{"message":"Server Error"}', { status: 502 }) : new Response(SHA_B);
    if (url === `https://api.github.com/repos/brave/brave-variations/contents/studies?ref=${SHA_B}`) return json([{ name: 'ZCashStudy.json5', type: 'file', sha: blobSha(STUDY) }]);
    if (url === `https://raw.githubusercontent.com/brave/brave-variations/${SHA_B}/studies/ZCashStudy.json5`) return new Response(STUDY);
    if (url === `https://raw.githubusercontent.com/brave/brave-core/master/${LOCKFILE}`) return new Response(lockOf(pkg('zcash', '1.0.0', { source: null, deps: ['orchard'] }), pkg('orchard', '0.15.0')));
    if (url === 'https://raw.githubusercontent.com/brave/brave-core/master/DEPS') return new Response(FORK_DEPS);
    // Outage: Zakura releases unavailable.
    if (url.startsWith('https://api.github.com/repos/zakura-core/zakura/releases')) return outage ? new Response('{"message":"Server Error"}', { status: 502 }) : json([{ tag_name: 'v4.0.0', published_at: '2026-09-30T12:00:00Z' }]);
    if (url.startsWith('https://api.github.com/repos/zakura-core/wallet-libraries/commits')) return json([{ commit: { message: 'Rewire onto Zakura Common', committer: { date: '2026-10-02T09:00:00Z' } } }]);
    return new Response('not found', { status: 404 });
  }) as typeof fetch;
}

test('R-EXTRA-2: through runRefresh, one answering pointer, unreachable brave-variations and a watch release outage keep last-good data and are recorded partial', async () => {
  await withDataDir(async (dir) => {
    const base = { trigger: 'test', token: null, log: quiet, sleep: async () => {}, collectors: [braveVersions, services, watch] };
    const r1 = await run.runRefresh({ ...base, now: '2026-10-08T10:00:00Z', fetchImpl: servicesWorld(false) });
    assert.deepEqual(r1.sources, { 'brave-versions': 'ok', 'brave-services': 'ok', watch: 'ok' }, 'healthy baseline run');
    const v1 = readData(dir, 'sources', 'brave-versions.json').data;
    const s1 = readData(dir, 'sources', 'brave-services.json').data;
    const w1 = readData(dir, 'sources', 'watch.json').data;
    assert.equal(s1.studies.length, 1);
    assert.equal(w1.items.find((i: { id: string }) => i.id === 'watch-zakura').updatedAt, '2026-09-30T12:00:00Z');

    const r2 = await run.runRefresh({ ...base, now: '2026-10-08T12:00:00Z', fetchImpl: servicesWorld(true) });
    assert.deepEqual(r2.sources, { 'brave-versions': 'partial', 'brave-services': 'partial', watch: 'partial' });
    assert.equal(r2.outcome, 'partial');
    assert.equal(r2.derive?.outcome, 'ok');

    // brave-versions: the Android release pointer (unreadable now) keeps its value and read time.
    const v2env = readData(dir, 'sources', 'brave-versions.json');
    const android = v2env.data.current.find((c: { platform: string; channel: string }) => c.platform === 'android' && c.channel === 'release');
    assert.equal(android.version, '1.96.61');
    assert.deepEqual(android.carriedPointers, { 'release-android-google-play': '2026-10-08T10:00:00Z' });
    assert.equal(v2env.data.current.length, v1.current.length, 'no platform/channel dropped');
    const desktop = v2env.data.current.find((c: { platform: string; channel: string }) => c.platform === 'desktop' && c.channel === 'release');
    assert.match(desktop.basis, /not confirmed for every desktop OS this run/);

    // brave-services: studies kept with their read time, gate3 refreshed independently.
    const s2env = readData(dir, 'sources', 'brave-services.json');
    assert.deepEqual(s2env.data.studies.map((s: { name: string }) => s.name), ['ZCashStudy_Enabled']);
    assert.equal(s2env.data.studiesReadAt, '2026-10-08T10:00:00Z');
    assert.equal(s2env.data.gate3.checkedAt, '2026-10-08T12:00:00Z');
    assert.equal(s2env.data.gate3.zcashDisabled, true);

    // watch: Zakura release metadata kept with the time it was read.
    const w2env = readData(dir, 'sources', 'watch.json');
    const zakura = w2env.data.items.find((i: { id: string }) => i.id === 'watch-zakura');
    assert.equal(zakura.updatedAt, '2026-09-30T12:00:00Z');
    assert.equal(zakura.latest, ' Latest release: v4.0.0.');
    assert.equal(zakura.metadataReadAt, '2026-10-08T10:00:00Z');

    const st = readData(dir, 'status.json').sources;
    for (const [id, e] of [['brave-versions', v2env], ['brave-services', s2env], ['watch', w2env]] as const) {
      assert.equal(e.partial, true, `${id}: envelope marked partial`);
      assert.equal(e.completeAt, '2026-10-08T10:00:00Z', `${id}: everything is at least as fresh as the complete run`);
      assert.equal(st[id].lastOutcome, 'partial', `${id}: not reported as clean success`);
      assert.equal(st[id].lastCompleteAt, '2026-10-08T10:00:00Z');
      assert.ok(st[id].limitations.length > 0, `${id}: says what was not refreshed`);
    }
    assert.ok(st['brave-versions'].limitations.some((l: string) => /26 pointer\(s\) unavailable.*26 kept from their last successful read/.test(l)));
    assert.ok(st['brave-services'].limitations.some((l: string) => /brave-variations could not be re-read .*keeping 1 study read at 2026-10-08T10:00:00Z/.test(l)));
    assert.ok(st.watch.limitations.some((l: string) => /zakura-core\/zakura: .*keeping the release metadata read at 2026-10-08T10:00:00Z/.test(l)));
  });
});

// ---------------------------------------------------------------------------
// R-WF: the failure report uses the refresh step's actual exit code and start time
// ---------------------------------------------------------------------------

interface Step { run: string; env: Record<string, string>; ifLine: string | null }

/** A step of refresh.yml: its run script (block or single line), env mapping and if: condition. */
function workflowStep(name: string): Step {
  const lines = readFileSync(new URL('../.github/workflows/refresh.yml', import.meta.url), 'utf8').split('\n');
  const start = lines.findIndex((l) => l.trim() === `- name: ${name}`);
  assert.ok(start >= 0, `step "${name}" present`);
  const indent = (l: string) => l.match(/^ */)![0].length;
  const keyIndent = indent(lines[start]) + 2;
  let end = lines.findIndex((l, i) => i > start && l.trim() && indent(l) < keyIndent);
  if (end === -1) end = lines.length;
  const body = lines.slice(start + 1, end);
  const out: Step = { run: '', env: {}, ifLine: null };
  for (let i = 0; i < body.length; i++) {
    const l = body[i];
    if (indent(l) !== keyIndent) continue;
    const m = l.trim().match(/^([\w-]+):\s*(.*)$/);
    if (!m) continue;
    const block = () => {
      const rows: string[] = [];
      for (let j = i + 1; j < body.length && (!body[j].trim() || indent(body[j]) > keyIndent); j++) rows.push(body[j]);
      return rows;
    };
    if (m[1] === 'if') out.ifLine = m[2];
    if (m[1] === 'env') for (const row of block()) { const kv = row.trim().match(/^(\w+):\s*(.*)$/); if (kv) out.env[kv[1]] = kv[2]; }
    if (m[1] === 'run') {
      if (m[2] !== '|') out.run = m[2];
      else {
        const rows = block();
        const bodyIndent = Math.min(...rows.filter((r) => r.trim()).map(indent));
        out.run = rows.map((r) => r.slice(bodyIndent)).join('\n');
      }
    }
  }
  return out;
}

const parseOutputs = (file: string): Record<string, string> => {
  if (!existsSync(file)) return {};
  return Object.fromEntries(readFileSync(file, 'utf8').split('\n').filter((l) => l.includes('=')).map((l) => [l.slice(0, l.indexOf('=')), l.slice(l.indexOf('=') + 1)]));
};

/** Resolve `${{ steps.refresh.outputs.X }}` expressions of a step's env against the refresh step's outputs. */
function resolveEnv(step: Step, outputs: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(step.env)) {
    if (/secrets\.|github\./.test(v)) continue;
    out[k] = v.replace(/\$\{\{\s*steps\.refresh\.outputs\.([\w-]+)\s*\}\}/g, (_, name) => outputs[name] ?? '');
  }
  return out;
}

/** Run the "Refresh sources" step with `node` replaced by `nodeStub` (a bash body), then the report step on its outputs. */
function simulate(root: string, nodeStub: string, extraEnv: Record<string, string> = {}): { refresh: { status: number | null; out: string }; outputs: Record<string, string>; report: { status: number | null; out: string } } {
  const bin = join(root, 'bin');
  mkdirSync(bin, { recursive: true });
  writeFileSync(join(bin, 'node'), `#!/bin/bash\n${nodeStub}\n`);
  chmodSync(join(bin, 'node'), 0o755);
  const outFile = join(root, 'github_output');
  rmSync(outFile, { force: true });
  const refreshStep = workflowStep('Refresh sources');
  // GitHub Actions runs `run:` blocks with bash -e (and -o pipefail for shell: bash).
  const r = spawnSync('bash', ['--noprofile', '--norc', '-eo', 'pipefail', '-c', refreshStep.run], { cwd: root, env: { PATH: `${bin}:${process.env.PATH}`, GITHUB_OUTPUT: outFile, ...extraEnv }, encoding: 'utf8' });
  const outputs = parseOutputs(outFile);
  const reportStep = workflowStep('Report refresh failure');
  const rep = spawnSync('bash', ['--noprofile', '--norc', '-eo', 'pipefail', '-c', reportStep.run], { cwd: root, env: { PATH: process.env.PATH, ...resolveEnv(reportStep, outputs) }, encoding: 'utf8' });
  return { refresh: { status: r.status, out: `${r.stdout}${r.stderr}` }, outputs, report: { status: rep.status, out: `${rep.stdout}${rep.stderr}` } };
}

test('R-WF: a refresh that crashes after writing a "success" run record is reported with its exit code, not as "outcome success"', () => {
  const root = mkdtempSync(join(tmpdir(), 'zbt-wf-'));
  try {
    // Real repro: the CLI writes status.json (outcome success, nothing collected), then crashes reading a corrupt runs.json.
    mkdirSync(join(root, 'data', 'history'), { recursive: true });
    writeFileSync(join(root, 'data', 'history', 'runs.json'), '{');
    const cli = new URL('../src/ingest/run.ts', import.meta.url).pathname;
    const sim = simulate(root, `exec "${process.execPath}" "${cli}" --only=none`, { TRACKER_DATA_DIR: join(root, 'data'), GITHUB_TOKEN: '', GH_TOKEN: '' });
    const status = JSON.parse(readFileSync(join(root, 'data', 'status.json'), 'utf8'));
    assert.equal(status.lastRun.outcome, 'success', 'precondition: the record written before the crash says success');
    assert.equal(sim.refresh.status, 1, `the step fails with the process exit code:\n${sim.refresh.out}`);
    assert.equal(sim.outputs.exit_code, '1', 'the exit code is a step output');
    assert.ok(Number.isFinite(Date.parse(sim.outputs.started ?? '')), 'the start time is a step output');
    assert.equal(sim.report.status, 1);
    assert.match(sim.report.out, new RegExp(`::error::Refresh failed \\(the refresh process exited with code 1 after recording run ${status.lastRun.id} started ${status.lastRun.startedAt} with outcome success; it crashed or was interrupted after writing that record, so the record does not show how the run ended\\)\\.`));
    assert.match(sim.report.out, /The refresh process exited with code 1\.$/m);
    assert.doesNotMatch(sim.report.out, /sources not ok: none/, 'no misleading "outcome success" reason');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('R-WF: a crash before any record is written names the earlier record as earlier; recorded failures keep their reason and add the exit code', () => {
  const root = mkdtempSync(join(tmpdir(), 'zbt-wf-'));
  try {
    mkdirSync(join(root, 'data'), { recursive: true });
    const earlier = { lastRun: { id: 'old111', startedAt: '2026-10-01T00:00:00.000Z', outcome: 'success', sources: { a: 'ok' }, derive: { outcome: 'ok', error: null } }, sources: {} };
    writeFileSync(join(root, 'data', 'status.json'), JSON.stringify(earlier));
    const killed = simulate(root, 'exit 137');
    assert.equal(killed.refresh.status, 137);
    assert.equal(killed.outputs.exit_code, '137');
    assert.equal(killed.report.status, 1);
    assert.match(killed.report.out, /::error::Refresh failed \(the refresh process exited with code 137 before writing a run record; the latest record \(run old111 started 2026-10-01T00:00:00\.000Z, outcome success\) is from an earlier refresh\)\./);

    // A derivation failure recorded by this refresh: the recorded reason, plus the exit code.
    const stub = [
      'now=$(date -u +%Y-%m-%dT%H:%M:%S.500Z)',
      'cat > data/status.json <<EOF',
      '{"lastRun":{"id":"new222","startedAt":"$now","outcome":"failed","sources":{"a":"ok","derive":"failed"},"derive":{"outcome":"failed","error":"Error: boom"}},"sources":{}}',
      'EOF',
      'exit 1',
    ].join('\n');
    const failed = simulate(root, stub);
    assert.equal(failed.refresh.status, 1);
    assert.match(failed.report.out, /::error::Refresh failed \(last recorded run new222 started \S+: derivation failed: Error: boom\)\. The published site keeps the previously derived data and its original generation time\. The refresh process exited with code 1\./);

    // A successful refresh step still records its exit code (0) and exits 0.
    const ok = simulate(root, 'exit 0');
    assert.equal(ok.refresh.status, 0);
    assert.equal(ok.outputs.exit_code, '0');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('R-WF: the report compares start times as instants and is wired to the refresh step outputs', () => {
  const report = workflowStep('Report refresh failure');
  assert.equal(report.ifLine, "always() && steps.refresh.outcome == 'failure'");
  assert.equal(report.env.REFRESH_EXIT_CODE, '${{ steps.refresh.outputs.exit_code }}');
  assert.equal(report.env.REFRESH_STARTED, '${{ steps.refresh.outputs.started }}');
  const runReport = (lastRun: unknown, env: Record<string, string>) => {
    const root = mkdtempSync(join(tmpdir(), 'zbt-wf-'));
    try {
      mkdirSync(join(root, 'data'));
      writeFileSync(join(root, 'data', 'status.json'), JSON.stringify({ lastRun, sources: {} }));
      const r = spawnSync('bash', ['--noprofile', '--norc', '-eo', 'pipefail', '-c', report.run], { cwd: root, env: { PATH: process.env.PATH, ...env }, encoding: 'utf8' });
      return `${r.stdout}${r.stderr}`;
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  };
  const rec = (startedAt: string) => ({ id: 'r1', startedAt, outcome: 'partial', sources: { a: 'partial' }, derive: { outcome: 'ok', error: null } });
  // The step's start time has whole seconds; the run's has milliseconds. Same second, later instant: this refresh.
  assert.match(runReport(rec('2026-10-08T20:00:00.500Z'), { REFRESH_EXIT_CODE: '1', REFRESH_STARTED: '2026-10-08T20:00:00Z' }), /after recording run r1 started 2026-10-08T20:00:00\.500Z with outcome partial/);
  assert.match(runReport(rec('2026-10-08T19:59:59.900Z'), { REFRESH_EXIT_CODE: '1', REFRESH_STARTED: '2026-10-08T20:00:00Z' }), /before writing a run record; the latest record \(run r1 started 2026-10-08T19:59:59\.900Z, outcome partial\) is from an earlier refresh/);
  // Without the outputs (e.g. the step was cancelled before writing them) the report still does not call a non-failed record the reason.
  assert.match(runReport(rec('2026-10-08T20:00:00.500Z'), {}), /the refresh process failed, but the latest run record \(run r1 started 2026-10-08T20:00:00\.500Z\) says outcome partial; the process crashed or was interrupted/);
});
